module.exports = {
  apps: [
    {
      name: "snalv",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        NEXTAUTH_URL: "http://localhost:3000",
        NEXTAUTH_SECRET: "57jseAh9H2EKVtcwMIMTvCwjoVhbMOp1WblP3tysTfJUHLWbwA",
        EMAIL_HOST: "smtps.aruba.it",
        EMAIL_PORT: 465,
        EMAIL_USER: "socioassistenziale@snalv.it",
        EMAIL_PASSWORD: "anaste18",
        EMAIL_FROM: "noreply@snalv.it",
        EMAIL_TO: "socioassistenziale@snalv.it",
        EMAIL_USER: "socioassistenziale@snalv.it",
        EMAIL_USER_CONTEGGI: "conteggi@snalv.it",
        EMAIL_USER_CONTATTI: "info@snalv.it",
        EMAIL_USER_ORGANIZZAZIONE: "organizzazione@snalv.it",
        EMAIL_PASSWORD: "anaste18",
        EMAIL_PASSWORD_CONTEGGI: "Conte24!",
        EMAIL_PASSWORD_CONTATTI: "Sindacato1!",
        EMAIL_PASSWORD_ORGANIZZAZIONE: "Organizza24!",
        EMAIL_FROM: "noreply@snalv.it",
        EMAIL_TO: "socioassistenziale@snalv.it",
        EMAIL_TO_CONTEGGI: "conteggi@snalv.it",
        EMAIL_TO_CONTATTI: "info@snalv.it",
        EMAIL_TO_ORGANIZZAZIONE: "organizzazione@snalv.it",
        NEXT_PUBLIC_BREVO_API_KEY:
          "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",
      },
    },
  ],
};
